### ISSUE TITLE
写真選択時にヌルポで落ちる

### ISSUE THREAD

**Issue by dictav** [dictav/AndroidSample-kotlin#12]
今日実機（nexus5）届いたから再度テストしてみたんだけど、写真選択時に落ちます

```
     Caused by: kotlin.KotlinNullPointerException
            at org.jetbrains.kotlin.gradle.androidsample.PickphotoActivity.pictureTurn(PickphotoActivity.kt:85)
            at org.jetbrains.kotlin.gradle.androidsample.PickphotoActivity.onActivityResult(PickphotoActivity.kt:52)
            at android.app.Activity.dispatchActivityResult(Activity.java:5423)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3361)
```

**Comment by dictav** [comment]
Fixed by #21
