### ISSUE TITLE
写真選択機能の実装

### ISSUE THREAD

**Issue by dictav** [dictav/AndroidSample-kotlin#6]
好きな写真をアップロードする際に、写真を選択する手段をユーザに提供する。
この時、考えられる手段は２つ。
1. Photoライブラリから写真を選択
2. カメラ撮影機能の実装

1 は必ず実装する必要がある。
2 はコストが低い場合は実装。

**Comment by dictav** [comment]
今日実機（nexus5）届いたから再度テストしてみたんだけど、写真選択時に落ちます

```
     Caused by: kotlin.KotlinNullPointerException
            at org.jetbrains.kotlin.gradle.androidsample.PickphotoActivity.pictureTurn(PickphotoActivity.kt:85)
            at org.jetbrains.kotlin.gradle.androidsample.PickphotoActivity.onActivityResult(PickphotoActivity.kt:52)
            at android.app.Activity.dispatchActivityResult(Activity.java:5423)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3361)
```
